Associations
HansZizold/School-Library pull request #3
Opened 2022-08-31 21:24 UTC by HansZizold

**CHANGES**
- A class Classroom was created.
- A relationship has-many/belongs-to between Classroom and Student was created. 

- A class Book was created.
- A class Rental was created.
- A relationship many-to-many between Person and Book using the intermediate class Rental was created.

Two additional test files were created for testing purposes.

2022-08-31 22:04 UTC, BenMukebo requested changes
### Hi @HansZizold,

You did a great job so far 👏🏼 👏🏼
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

### To highlight 💪🏻

- No linter errors. ✔️ 
- Gitflow was correctly used.  ✔️   
- Descriptive README file.  ✔️ 
 👍  Good job!


## STATUS: CHANGES REQUESTED  ♻️ 
_Please Check the comments under the review and make all required changes_

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏 💻  
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me @BenMukebo when you comment so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-31 22:04 UTC, BenMukebo commented on person.rb
> +# p capitalized_trimmed_person.correct_name
- [ ] Please do not leave unused code as a comment in your codebase. unused code as comments makes your code not clean. Kindly remove all unused code this will make your code much noise, It is always a good practice to keep your code clean from such comments.

2022-08-31 22:04 UTC, BenMukebo commented on student.rb
>    def play_hooky
- [ ] When setting the classroom for a student it should also add it to the classroom's students, you should have a method that serves as the 'belongs-to' side (a student belongs to a classroom).

```ruby
def classroom=(classroom)
      @classroom = classroom
      classroom.students.push(self) unless classroom.students.include?(self)
  end
```

2022-08-31 22:04 UTC, BenMukebo commented on book.rb
> +  attr_reader :rentals
- [ ]  According to the project requirements, you should write two methods to get and set `rentals` and Ruby offers you a nice way to create your getters and setters! you can declare them by using :

```ruby
attr_reader :rentals
attr_writer :rentals
# Or you can make it even shorter by using:
attr_accessor :rentals
```
 Actually, you only have a getter method `attr_reader`. In order to make sure the Getters and Setters for @rentals are present, we need to add a setter method, `attr_writer`.


```ruby
  attr_accessor :title, :author, :rentals
```
Here is a [link](https://github.com/microverseinc/curriculum-ruby/blob/main/oop/articles/oop_principles_examples.md#useful-shortcuts-attr_reader-attr_writer-and-attr_accessor%20#%20*:name%20and%20:age%20instance%20variables%20are%20the%20only%20ones%20that%20should%20be%20able%20to%20be%20modified%20that's%20why%20they%20are%20defined%20as%20attr_accessors%20(here%20both%20Getters%20and%20Setters%20are%20defined)) to the example in a previous lesson: 

Note: You can achieve that by using atrr_reader, attr_writer / attr_accessor, or by writing getters and setters as plain methods ALL OPTIONS are correct as long as getters and setters are created for @rentals

2022-08-31 22:04 UTC, BenMukebo commented on book.rb
> +  end
- [OPTIONAL] You need to create the `many-to-many` (also `has-many-through`) relationship between `Person` and `Book` using the intermediate class `Rental`.  Great job creating a method for adding rentals but it should look like this: 

```ruby
  def add_rental(person, date)
    # *the book itself should be sent as a parameter to create the new rental achieving the 'has-many' association. 
    Rental.new(date, self, person)
  end
```

Here is a [link](https://github.com/microverseinc/curriculum-ruby/blob/main/oop/articles/oop_relationships_by_examples.md#many-to-many-relationship) to the example in a previous lesson:

2022-08-31 22:04 UTC, BenMukebo commented on person.rb
>    attr_accessor :name, :age
- [ ]  Kindly make sure the Getters and Setters for @rentals are present:

```ruby
  attr_accessor :name, :age, :rentals
```

2022-08-31 22:04 UTC, BenMukebo commented on person.rb
>  end
- [OPTIONAL] Great job creating a method for adding rentals  👍🏻 but it should look like this:

```ruby
 def add_rental(book, date)
    # *The person itself should be sent as a parameter to create the new rental achieving the 'has-many' association
    Rental.new(date, book, self)
  end
```

Here is a [link](https://github.com/microverseinc/curriculum-ruby/blob/main/oop/articles/oop_relationships_by_examples.md#many-to-many-relationship`) to the example in a previous lesson:

2022-08-31 23:19 UTC, HansZizold commented
@BenMukebo, very sorry. I don't understand the observations.
Please could you clarify?

2022-08-31 23:32 UTC, BenMukebo commented
Hey @HansZizold, Give me 20 minutes, I'll give you more details about what you need to do 👍🏻

2022-09-01 00:22 UTC, HansZizold commented
@BenMukebo, thank you very much for your observations and suggestions. 
I implemented all.

2022-09-01 00:33 UTC, addod19 approved these changes
Hi @HansZizold, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### Highlights
- [ ] Nice job addressing the comments by the previous code reviewer :rocket: awesome  :+1: 
- [ ] README is descriptive :100: 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-01 10:46 UTC, merged